#!/usr/bin/env python3
import sys
import os
import importlib
if len(sys.argv) < 2:
	print(f'{os.path.basename(sys.argv[0])}: usgage testmod module [..module ..module]',file=sys.stderr)
	sys.exit(1)
for module in sys.argv[1:]:
	try:
		importlib.import_module(module)
	except:
		print('error importing module',module,file=sys.stderr)
		sys.exit(1)
sys,exit(0)
